def test_esp_timer(dut):
    dut.expect("TEST start esp_timer", timeout=30)
    dut.expect("monotonic=ok", timeout=30)
    dut.expect("delay_lower=ok", timeout=30)
    dut.expect("delay_upper=ok", timeout=30)
    dut.expect("create=ok", timeout=30)
    dut.expect("fired_lower=ok", timeout=30)
    dut.expect("fired_upper=ok", timeout=30)
    dut.expect("after_stop=ok", timeout=30)
    dut.expect("TEST done", timeout=30)
